version:  '3.9'
services:
  product-Service:
    image:  product-image
    container_name: product-Service
    build:  userProductService-pc1/
    restart:  always
    networks:
      - product_net
    ports:
      - 9100:9100
    depends_on:
      - mongoService
      - apigateway

  mongoService:
    image:  mongo
    container_name: mongo-service
    ports:
      - 27017:27017
    networks:
      - product_net

  authentication-service:
    image:  authentication-image
    container_name: authentication-service
    build:  userAuthentication-pc1/
    restart:  always
    networks:
      - product_net
    ports:
      - 9200:9200
    depends_on:
      - mysqlService
      - apigateway

  mysqlService:
    image:  mysql:latest
    container_name: mysql-service
    networks:
      - product_net
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:  root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  apigateway:
    container_name: apigateway
    build:  SpringCloudAPIGateway/
    networks:
      - product_net
    ports:
      - 9000:9000

networks:
  product_net:
    driver: bridge



