FROM openjdk
WORKDIR usr/lib
ADD ./target/userProductService-pc1-0.0.1-SNAPSHOT.jar /usr/lib/userProductService-pc1-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","userProductService-pc1-0.0.1-SNAPSHOT.jar"]